// Step 1 verification: routing shell (hash router, nav tabs, Docs, Roadmap).
import { chromium } from 'playwright'

const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1600, height: 950 } })
const errs = []
p.on('pageerror', (e) => errs.push('PAGEERROR ' + e.message))
p.on('console', (m) => { if (m.type() === 'error') errs.push('CONSOLE ' + m.text()) })

await p.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await p.waitForFunction(() => window.__store?.getState().dataset, undefined, { timeout: 60000 })
await p.waitForTimeout(1500)

const tabs = () => p.$$eval('.topnav a', (a) => a.map((x) => `${x.textContent}${x.classList.contains('on') ? '*' : ''}`))
console.log('\n1. EXPLORER (default)')
console.log('   hash   :', await p.evaluate(() => location.hash || '(empty)'))
console.log('   tabs   :', (await tabs()).join('  '))
console.log('   ctx    :', await p.$$eval('.ctx .cell .k', (n) => n.map((x) => x.textContent).join(' | ')))
console.log('   panels :', (await p.$$eval('.panel-head h2', (n) => n.map((x) => x.textContent))).join(', '))
await p.screenshot({ path: 'screenshots/step1-explorer.png' })

console.log('\n2. DOCS')
await p.click('.topnav a[href="#/docs"]')
await p.waitForSelector('.docs-body h1', { timeout: 30000 })
await p.waitForTimeout(700)
console.log('   hash   :', await p.evaluate(() => location.hash))
console.log('   tabs   :', (await tabs()).join('  '))
console.log('   ctx    :', (await p.$$('.ctx')).length ? 'SHOWN (should be hidden)' : 'hidden on doc pages')
console.log('   toc    :', await p.$eval('.docs-meta', (n) => n.textContent))
console.log('   toc[0:6]:', (await p.$$eval('.docs-toc a', (a) => a.slice(0, 6).map((x) => x.textContent))).join(' / '))
console.log('   h1 count:', await p.$$eval('.docs-body h1[id]', (n) => n.length))
console.log('   h2 count:', await p.$$eval('.docs-body h2[id]', (n) => n.length))
console.log('   tables  :', await p.$$eval('.docs-body table', (n) => n.length))
console.log('   mermaid :', await p.$$eval('.docs-body code.language-mermaid', (n) => n.length), 'as plain code blocks')
console.log('   first h1:', await p.$eval('.docs-body h1', (n) => `#${n.id} — ${n.textContent}`))
await p.screenshot({ path: 'screenshots/step1-docs.png' })

// deep link + TOC jump + active tracking
await p.click('.docs-toc .toc-grp:nth-child(9) > a')
await p.waitForTimeout(600)
console.log('   after TOC click, active:', await p.$eval('.docs-toc a.on', (n) => n.textContent))
console.log('   subsections shown:', await p.$$eval('.docs-toc a.lvl2', (n) => n.length), 'for the open chapter only')
await p.screenshot({ path: 'screenshots/step1-docs-deep.png' })

console.log('\n3. ROADMAP')
await p.click('.topnav a[href="#/roadmap"]')
await p.waitForSelector('.rm-inner', { timeout: 30000 })
await p.waitForTimeout(600)
console.log('   hash   :', await p.evaluate(() => location.hash))
console.log('   tabs   :', (await tabs()).join('  '))
console.log('   secs   :', (await p.$$eval('.rm-sec > h2', (n) => n.map((x) => x.textContent))).join(' | '))
console.log('   tags   :', (await p.$$eval('.rm-list .badge', (n) => n.map((x) => x.textContent))).join(' '))
console.log('   §8 items:', await p.$$eval('.rm-md li', (n) => n.length))
console.log('   §8 first:', (await p.$eval('.rm-md li', (n) => n.textContent)).slice(0, 90) + '…')
await p.screenshot({ path: 'screenshots/step1-roadmap.png', fullPage: false })
await p.evaluate(() => document.querySelector('.roadmap').scrollTo(0, 99999))
await p.waitForTimeout(400)
await p.screenshot({ path: 'screenshots/step1-roadmap-end.png' })

console.log('\n4. BACK BUTTON + DIRECT LOAD')
await p.goBack(); await p.waitForTimeout(600)
console.log('   after Back, hash:', await p.evaluate(() => location.hash), '· active tab:', await p.$eval('.topnav a.on', (n) => n.textContent))
const p2 = await b.newPage({ viewport: { width: 1600, height: 950 } })
await p2.goto('http://localhost:5173/#/roadmap', { waitUntil: 'networkidle' })
await p2.waitForSelector('.rm-inner', { timeout: 30000 })
console.log('   direct #/roadmap loads:', await p2.$eval('.topnav a.on', (n) => n.textContent))
await p2.close()

console.log('\n5. BACK TO EXPLORER — nothing lost')
await p.click('.topnav a[href="#/"]')
await p.waitForTimeout(1200)
console.log('   panels :', (await p.$$eval('.panel-head h2', (n) => n.map((x) => x.textContent))).join(', '))
console.log('   dataset:', await p.evaluate(() => window.__store.getState().dataset?.meta.region))
await p.screenshot({ path: 'screenshots/step1-back-to-explorer.png' })

console.log('\nerrors:', errs.length ? errs : 'none')
await b.close()
