import { chromium } from 'playwright'
const b = await chromium.launch({ args: ['--use-gl=angle','--use-angle=d3d11','--enable-gpu','--ignore-gpu-blocklist'] })
const p = await b.newPage({ viewport: { width: 1680, height: 950 } })
p.on('pageerror', e => console.log('PAGEERR', e.message))
await p.goto('http://localhost:5173/', { waitUntil: 'networkidle' })
await p.waitForSelector('.scene-host canvas')
await p.waitForFunction(() => !document.querySelector('.scene-busy'), null, { timeout: 300000 })
await p.waitForTimeout(3500)
await p.getByRole('button', { name: /Isosurface/ }).click()
await p.waitForTimeout(1400)
await p.getByRole('button', { name: /Current flow lines/ }).click()
await p.waitForTimeout(1200)
await p.mouse.move(8,8); await p.waitForTimeout(600)
await p.locator('.scene-panel').screenshot({ path: 'screenshots/spike-f00.png' })
// step to a far frame so the pattern change is obvious side by side
for (let i=0;i<9;i++){ await p.evaluate(()=>document.querySelector('.tl-transport button:nth-child(3)').click()); await p.waitForTimeout(120) }
await p.waitForTimeout(500); await p.mouse.move(8,8); await p.waitForTimeout(500)
await p.locator('.scene-panel').screenshot({ path: 'screenshots/spike-f09.png' })
// deeper level -- amplitude decays and the pattern twists
await p.evaluate(()=>document.querySelectorAll('.tl-levels button')[2].click())
await p.waitForTimeout(700); await p.mouse.move(8,8); await p.waitForTimeout(500)
await p.locator('.scene-panel').screenshot({ path: 'screenshots/spike-300m.png' })
await p.evaluate(()=>document.querySelectorAll('.tl-levels button')[0].click())
await p.waitForTimeout(700)
// full dashboard: every disclosure on at once
await p.screenshot({ path: 'screenshots/spike-full.png' })
console.log('FOOTER:', (await p.locator('.appfoot').innerText()).split('\n').join(' | '))
console.log('CHIP:', await p.locator('.synth-chip').innerText())
console.log('APPBAR DATE:', await p.locator('.appbar .cell', { hasText: 'Date' }).innerText())
await b.close()
